### ISSUE TITLE
rpi-node 0.12.0 -> Illegal instruction on RPi B

### ISSUE THREAD

**Issue by StefanScherer** [hypriot/rpi-node#1]
Running `npm` or `node` in the rpi-node:0.12.0 container on a Raspberry Pi B crashes:

```
Step 4 : RUN npm install
 ---> Running in 2b93bf701b2d
Illegal instruction
```

**Comment by seal-ss** [comment]
Workaround at the moment is using `FROM hypriot/rpi-iojs:latest`

**Comment by juliocesar-io** [comment]
I got this with `rpi-node:0.12.0`

```
root@xx:/# node -v
v0.12.0
root@xx:/# node app.js
Illegal instruction (core dumped)
root@xx:/ npm -v
Illegal instruction (core dumped)

```

Something went wrong. I will try the iojs image.

**Comment by StefanScherer** [comment]
fixed with node 4

**Comment by qfournier** [comment]
I have an "exec error" with rpi-node:0.12.0 and "RUN npm install"... I believe it is the same error, how did you manage to solve it ?

**Comment by StefanScherer** [comment]
@kentin19 Please update to Node 4 or 5. These images work for Pi B again. 

FROM hypriot/rpi-node:4.4.0

**Comment by qfournier** [comment]
I used rpi-node:4.4.0 and 5.8.0 on Ubuntu 14.04 LTS (Intel processor) but still have the "exec format error"

**Comment by StefanScherer** [comment]
@kentin19 Oh that's the problem. For Intel please use the upstream Docker image node:4.4.0. The rpi-node is for ARM CPUs.

**Comment by qfournier** [comment]
My bad, I thought rpi-node was also for Intel architecture ! It works, thank you very much.
